name: quest_bluetoot_dev
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  intl: ^0.17.0
  flutter_blue_plus: ^1.4.0
  rxdart: ^0.27.7
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.1
  bot_toast: ^4.0.3
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true
